### ISSUE TITLE
这个脚本把扩展smartUp手势搞废了

### ISSUE THREAD

**Issue by itheabyss** [WCY-dt/NoMoreRestrict#1]
本来碰到链接我反手一拖，就会在后台打开。装了这个后，没法拖了，这太狠了。

**Comment by WCY-dt** [comment]
已修复。

原来的脚本直接禁止了对拖动事件的劫持，导致 smartup 无法正常工作。考虑到拖动比较常用，新版本取消了对拖动的限制。

WCY-dt/NoMoreRestrict@c91ef423a7e482cb8196d561046f471c4eb9b357
