### ISSUE TITLE
在b站直播时有问题

### ISSUE THREAD

**Issue by itheabyss** [WCY-dt/NoMoreRestrict#2]
B站直播时，右键点击画面，会有菜单显示视频信息，切换线路，切换解码器等功能，但是装了这个后没了，右键点击直接出现浏览器的菜单。

应该说不止是直播，在B站视频页面也是一样的情况。

刚试了一下，抖音的视频也是一样。应该是脚本把所有视频的右键功能都给限了

**Comment by WCY-dt** [comment]
已修复。

现在增加了设置菜单，可以选择是否在视频网站上禁用默认的右键菜单。
